apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  app: mystok-gcp-dev
nameSuffix: -dev
patches:
- target:
    kind: Ingress
    name: mystok-ingress
  path: ./kustomize/static_ip.yaml
- target:
    kind: ManagedCertificate
    name: mystok-gcp-ssl-cert
  path: ./kustomize/domain.yaml
- target:
    kind: Deployment
    name: mystok-gcp-deploy
  path: ./kustomize/ref_secret_name.yaml
- target:
    kind: Deployment
    name: mystok-gcp-deploy
  path: ./kustomize/recreate_strategy.yaml
