apiVersion: apps/v1
kind: Deployment
metadata:
  name: mystok-gcp-deploy
spec:
# does not work
#  strategy:
#    type: "Recreate"
  template:
    spec:
      containers:
      - name: cloud-sql-proxy
        env:
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: mystok-gcp-cloudsqlproxy-env-dev
      - name: mystok-gcp-tomcat
        image: dekabitasp/mystok-gcp-app-dev
      volumes:
      - name: mystok-gcp-cloudsqlproxy-sa-secret-volume
        secret:
          secretName: mystok-gcp-cloudsqlproxy-sa-secret-dev
      - name: mystok-gcp-gke-to-cloudstorage-sa-secret-volume
        secret:
          secretName: mystok-gcp-gke-to-cloudstorage-sa-secret-dev

