apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mystok-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mystok-gcp-ip-dev
    networking.gke.io/managed-certificates: mystok-gcp-ssl-cert-dev
