apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mystok-gcp-dev
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/dev
    repoURL: 'https://github.com/T41-Ch1/mystok-gcp-k8s.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
