apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- sealed
commonLabels:
  app: mystok-gcp-prod
nameSuffix: -prod
patches:
- target:
    kind: Ingress
    name: mystok-ingress
  path: ./kustomize/staticip_mcrt.yaml
- target:
    kind: ManagedCertificate
    name: mystok-gcp-ssl-cert
  path: ./kustomize/domain.yaml
- target:
    kind: Deployment
    name: mystok-gcp-deploy
  path: ./kustomize/ref_secret_name.yaml
images:
- name: dekabitasp/mystok-gcp-app-prod
  newName: dekabitasp/mystok-gcp-app-prod
  newTag: 20210128-1617 # {"$imagepolicy": "flux-system:mystok-gcp-k8s:tag"}
