apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  app: mystok-gcp-prod
nameSuffix: -prod
patches:
- target:
    kind: Ingress
    name: mystok-ingress
  path: static_ip.yaml
patchesJson6902:
- target:
    kind: ManagedCertificate
    name: mystok-gcp-ssl-cert
  path: domain.json

