apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  app: prod-mystok-gcp
namePrefix: prod-
patches:
- target:
    kind: ManagedCertificate
    name: mystok-gcp-ssl-cert
  path: domain.json
- target:
    kind: Ingress
    name: mystok-ingress
  path: static_ip.yaml
