apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ./sealed
#- sealed-prod-mystok-gcp-cloudsqlproxy-env.yaml
#- sealed-prod-mystok-gcp-cloudsqlproxy-sa-secret.yaml
#- sealed-prod-mystok-gcp-gke-to-cloudstorage-sa-secret.yaml
commonLabels:
  app: mystok-gcp-prod
nameSuffix: -prod
patches:
- target:
    kind: Ingress
    name: mystok-ingress
  path: ./kustomize/static_ip.yaml
- target:
    kind: ManagedCertificate
    name: mystok-gcp-ssl-cert
  path: ./kustomize/domain.yaml
- target:
    kind: Deployment
    name: mystok-gcp-deploy
  path: ./kustomize/ref_secret_name.yaml
