apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mystok-gcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/T41-Ch1/mystok-gcp-k8s.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
