apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/T41-Ch1/mystok-gcp-k8s
- mystok-gcp-app-hpa.yaml
- mystok-gcp-app-service.yaml
- mystok-gcp-ingress.yaml
- mystok-gcp-ssl-cert.yaml
