apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./mystok-gcp-app-deployment.yaml
- mystok-gcp-app-hpa.yaml
- mystok-gcp-app-service.yaml
- mystok-gcp-ingress.yaml
- mystok-gcp-ssl-cert.yaml
